name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq wixl git
        
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make all

      - name: Test
        run: make test
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_REGION:   ${{ secrets.TEST_REGION   }}
          REPO_URL:      ${{ secrets.REPO_URL      }}
          TEST_GROUP:    ${{ secrets.TEST_GROUP    }}
          TEST_APPID:    ${{ secrets.TEST_APPID    }}
